### ISSUE TITLE
Allowable value for the Long conversion should be set to 0x00 - 0x7FFFFFFFFFFFFFFF

### ISSUE THREAD

**Issue by romanolester** [ingonoka/BERTLV-ANDROID#2]
https://github.com/ingonoka/BERTLV-ANDROID/blob/eefdf6016a5186ecfe907e5969c4e1180bca957e/bertlvlib/src/main/kotlin/com/ingonoka/bertlv/utils/LongExt.kt#L22

Condition should use `0x7FFFFFFFFFFFFFFF` instead of `0xFFFFFFFF`

**Comment by ingonoka** [comment]
Fixed in v0.4
